name: update about project
on:
  push:
    branches:
      - main
      - develop
  fork:
  watch:
    types:
      - started
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: update about project
        uses: ouuan/This-repo-has-x-stars-y-forks-action@v2
        with:
          token: ${{ secrets.STAR_FORK_TOKEN }}
          template: "REST API created with Spring Boot, PostgreSQL, <starCount> stars and <forkCount> forks."
